# Generated by Django 3.0.5 on 2022-04-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20220414_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilayaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=100)),
                ('cas', models.IntegerField()),
            ],
        ),
    ]
