# Generated by Django 3.0.5 on 2022-04-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_wilayadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wilayadata',
            options={'managed': True, 'verbose_name': 'ModelName', 'verbose_name_plural': 'virus Case wilaya'},
        ),
        migrations.AlterModelTable(
            name='wilayadata',
            table='',
        ),
    ]
