# Generated by Django 3.0.5 on 2022-04-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
