# Generated by Django 3.0.5 on 2022-06-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20220423_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentresOfVaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centreId', models.PositiveIntegerField(null=True)),
                ('doctorNumber', models.PositiveIntegerField(null=True)),
                ('Adresse', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
